export function Footer(){
  return(
      <footer className="bg-gray-800 text-white mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className='text-center'>
            <p className='text-gray-300'>
              generated by JYR
            </p>
          </div>
        </div>
      </footer>
  )
}