'use client';
import Link from 'next/link';
import { useState } from 'react';
import { SDGS_GOALS } from './sdgs/sdgs-data';


export default function Home(){
  const [hoveredGoal, setHoveredGoal] = useState<number | null>(null);
  
  return(
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-green-50">
      <header className="bg-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-6">
              <h1 className="text-3xl font-bold text-gray-900">JYR. ポータル</h1>
              <nav className="hidden md:flex space-x-8">
                <Link href="/sdgs" className="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium transition-colors">
                  ダッシュボード
                </Link>
                <Link href="/policy" className="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium transition-colors">
                  政策効果
                </Link>
              </nav>
          </div>
        </div>
      </header>
      
      <main className="max-w-7x1 mx-auto px-4 sm:px6 lg:px-8 py-12">
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold text-gray-900 mb-10">
            JYR. ポータル(変更前)
          </h1>
          <p className="text-xl text-gray-600 max-w-3x1 mx-auto">本ダッシュボードは、日本全国の市区町村ごとのSDGs（持続可能な開発目標）の達成度をスコアとして可視化し、それぞれの地域における政策の効果や課題を一目で把握できるように設計されたツールです。</p>
        </div>

      <div className="flex flex-wrap justify-center gap-4 mb-16">
        <Link 
          href="/sdgs" 
          className="relative text-white px-12 py-8 rounded-xl font-bold text-lg min-h-[200px] min-w-[300px] flex items-center justify-center transition-all shadow-2xl hover:shadow-3xl transform hover:-translate-y-2 overflow-hidden"
          style={{
            backgroundImage: "url('/sdgs-logo.png')",
            backgroundSize: 'cover',
            backgroundPosition: 'center'
          }}
        >
        </Link>
      </div>

      {/* SDGs目標グリッド */}
      <div className="mb-16">
        <h3 className="text-2xl font-bold text-gray-900 mb-8 text-center">17の持続可能な開発目標</h3>
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          {SDGS_GOALS.map((goal) => (
            <div
              key={goal.id}
              className="rounded-lg p-6 text-white cursor-pointer transform transition-all duration-300 hover:scale-105 hover:shadow-xl"
              style={{ backgroundColor: goal.color }}
              onMouseEnter={() => setHoveredGoal(goal.id)}
              onMouseLeave={() => setHoveredGoal(null)}
            >
              <div className="text-center">
                <div className="flex justify-center mb-3">
                  <img 
                    src={`/sdgs_goals_icons/${goal.id}.png`}
                    alt={`SDG ${goal.id} アイコン`}
                    className="w-24 h-24 object-contain bg-white bg-opacity-20 rounded-lg p-3"
                  />
                </div>
                <div className="text-2xl font-bold mb-2">{goal.id}</div>
                <h4 className="font-semibold text-sm leading-tight mb-2">{goal.title}</h4>
                {hoveredGoal === goal.id && (
                  <p className="text-xs opacity-90 leading-relaxed">{goal.description}</p>
                )}
              </div>
            </div>
          ))}
          </div>
        </div>
      </div>
      </main> 
      <footer className="bg-gray-800 text-white mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">{/*レスポンシブデザインに必要*/}
          <div className='text-center'>
            <p className='text-gray-300'>
              generated by JYR
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}